In [5]:
# jupyter magics
%matplotlib inline
%config IPCompleter.greedy=True

# multiple output
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
# built-in types
myList1 = [10, 20, 1]
myList2 = list(range(10)) + myList1
mySet   = set(myList2)
myStr1  = "Hello"
myStr2  = ' world!'
myStr3  = myStr1 + myStr2
myDict  = {'list1': myList1, 'list2': myList2, 'set': mySet, 'strList': myStr3.split(' ')}  

print(myList1)
print(myList2)
print(mySet)
print(myStr3)
print(myDict)


[10, 20, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 1]
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20}
Hello world!
{'list1': [10, 20, 1], 'list2': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 1], 'set': {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20}, 'strList': ['Hello', 'world!']}


In [4]:
# numpy 
import numpy as np

myAr1 = np.array(myList2)
myAr2 = np.random.normal(size=(4, 4))

print(myAr1)
print(myAr2)

[ 0  1  2  3  4  5  6  7  8  9 10 20  1]
[[-0.12427349 -0.04556924 -0.13225301  0.35306921]
 [ 1.04421544 -0.77526302 -2.23299668  2.04725808]
 [ 1.01725373 -0.54090066  1.28421501 -1.03078033]
 [-0.7212302   1.34454039 -0.94499381 -0.0170201 ]]


In [26]:
# scipy
from scipy import linalg
myInvAr2 = linalg.inv(myAr2)

print(myInvAr2)

[[-0.12467508  0.22940877  0.1577673   1.16878545]
 [ 0.4991065   0.03033028 -0.27178403  1.01699146]
 [ 0.08576373  0.1649798   0.26308612 -0.21842557]
 [ 0.28994499 -0.40619633  0.15007667 -0.35645059]]
